---
- hosts: all
  remote_user: vagrant
  gather_facts: no
  sudo: false
  tasks:
  - shell: mkdir ~/.rbenv
  - shell: chdir=~/.rbenv git clone git://github.com/sstephenson/rbenv.git
  - shell: echo 'export PATH="$HOME/.rbenv/rbenv/bin:$PATH"' >> ~/.bash_profile
  - shell: echo 'eval "$(rbenv init -)"' >> ~/.bash_profile

  - git: repo=git://github.com/sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build clone=yes

  - shell: echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bash_profile
  - shell: bash -lc 'source ~/.bash_profile'
  - shell: bash -lc '$HOME/.rbenv/rbenv/bin/rbenv install -v 2.3.0'
  - shell: bash -lc '$HOME/.rbenv/rbenv/bin/rbenv global 2.3.0'
  - shell: bash -lc '$HOME/.rbenv/rbenv/bin/rbenv rehash'
  - shell: 'echo "gem: --no-rdoc --no-ri" > ~/.gemrc'
  - shell: bash -lc 'gem install bundler'
  - command: chdir="~/site" bundle install
    environment:
      PATH: /home/vagrant/.rbenv/versions/2.3.0/bin
      GEM_PATH: /home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0
